title         = "RBras"
baseurl = "http://leg.ufpr.br/~ara/rbras_test/" #alterar
theme = "roxo-hugo"
summarylength = 25
DefaultContentLanguage = "pt"
googleAnalytics = ""  # add your tracking id

[languages]
  [languages.pt]
    languageCode = "pt-BR"
    languageName="pt"
    contentDir = "content/pt"

  [languages.en]
    languageCode = "en-GB"
    languageName="en"
    contentDir = "content/en"

  
# Site Menus
[menu]
  # Navbar Menus
  [[languages.pt.menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[languages.en.menu.nav]]
    name    = "Home"
    url     = "en/"
    weight  = 1
  [[languages.pt.menu.nav]]
    name    = "Sobre"
    url     = "about"
    weight  = 2
  [[languages.en.menu.nav]]
    name    = "About"
    url     = "en/about"
    weight  = 2
  [[languages.pt.menu.nav]]
    name    = "Eventos"
    url     = "events"
    weight  = 3
  [[languages.en.menu.nav]]
    name    = "Events"
    url     = "en/events"
    weight  = 3
  [[languages.pt.menu.nav]]
    name    = "Notícias"
    url     = "blog"
    weight  = 4
  [[languages.en.menu.nav]]
    name    = "News"
    url     = "en/blog"
    weight  = 4
  [[languages.pt.menu.nav]]
    name    = "Associados"
    url     = "associado"
    weight  = 5
  [[languages.en.menu.nav]]
    name    = "Members"
    url     = "en/associado"
    weight  = 5
  [[languages.pt.menu.nav]]
    name    = "JP-Rbras"
    url     = "jp"
    weight  = 6
  [[languages.en.menu.nav]]
    name    = "JP-Rbras"
    url     = "en/jp"
    weight  = 6
  [[languages.pt.menu.nav]]
    name    = "Publicações"
    url     = "publicacoes"
    weight  = 7
  [[languages.en.menu.nav]]
    name    = "Publications"
    url     = "en/publicacoes"
    weight  = 7
  [[languages.pt.menu.nav]]
    name    = "Contato"
    url     = "contact"
    weight  = 8
  [[languages.en.menu.nav]]
    name    = "Contact"
    url     = "en/contact"
    weight  = 8

# Site Params
[params]
  logo = "images/logo.png"
  logo_footer = "images/logo-footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Adapted from Roxo Hugo themes | Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  
  
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "First Name"
    placeholder_last_name         = "Last Name"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/bg-br2.png"
    heading               = "RBras"
    tagline               = "Região Brasileira da Sociedade Internacional de Biometria"
    tagline2              = "Brazilian Region of International Biometric Society"
    primary_button        = "Eventos"
    primary_button2       = "Events" 
    primary_button_url    = "events"
    secondary_button      = "Contato"
    secondary_button2     = "Contact"
    secondary_button_url  = "contact"
    

  [params.blog]
    read_more             = "Ler Mais"

  [params.portfolio]
    enable    = true
    title     = "OUR RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/member-background.jpg"
    title               = "SEJA UM ASSOCIADO"
    title2              = "BECOME A MEMBER"
    primary_button      = "Contato"
    primary_button2     = "Contat"
    primary_button_url  = "contact"
    primary_button_url2  = "en/contact"
    secondary_button    = "Saiba Mais"
    secondary_button2    = "Informations"
    secondary_button_url2 = "en/associado"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Informações para Contato"
      address = "presidente@rbras.org.br"
      phone   = "tesouraria@rbras.org.br"
      email   = "secretaria@rbras.org.br"
      # Footer Sitemap
#      [params.footer.sitemap]
#        title   = "Sitemap"
#        [[params.footer.sitemap.link]]
#          name = "About Company"
#          url  = "about"
#        [[params.footer.sitemap.link]]
#          name = "Projects"
#          url  = "portfolio"
#        [[params.footer.sitemap.link]]
#          name = "Blog"
#          url  = "blog"
#        [[params.footer.sitemap.link]]
#          name = "Contact"
#          url  = "contact"
      # Footer Social Media
#      [params.footer.social]
#        title   = "Social Media"
#        [[params.footer.social.link]]
#          name = "Medium"
#          url  = "#"
#        [[params.footer.social.link]]
#          name = "Behance"
#          url  = "#"
#        [[params.footer.social.link]]
#          name = "Dribbble"
#          url  = "#"
#        [[params.footer.social.link]]
#          name = "Instagram"
#          url  = "#"
      # Footer Service
#      [params.footer.service]
#        title       = "We help brands:"
#        description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
#      [params.footer.back_to_top]
#        description = "I want to <br> visit again"
